### ISSUE TITLE
website deploy

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/NCC-workshop#1]
Hi @jeffreyhanson,

Would you mind having a quick peak at the workshop website deploy?
I am not entirely sure how to do this.

Thanks!

**Comment by jeffreyhanson** [comment]
Sure - on it now.

**Comment by jeffreyhanson** [comment]
I might have to clone the repo and play around with somethings to get it working. This will prolly require some changes to the main branch - is that ok? Or should I wait until you've finished working on it?

**Comment by ricschuster** [comment]
Thanks very much Jeff!
Please go ahead and make changes as you see fit.

**Comment by jeffreyhanson** [comment]
@ricschuster, I think I've got it all working now. To make updates, you should only need to edit the Rmarkdown files and GitHub Actions will automatically build the site and pdf version of the manual. 

Also, once you've got this working and looking good. I wonder if it would be worth make a copy of this to serve as the "main" workshop repository, which we would simply copy as needed to create future workshops? I wonder if the template stuff on GitHub would be useful for this? What do you think?

**Comment by jeffreyhanson** [comment]
Also, the workshop uses lpsymphony. In terms of making the installation process easier for attendees, it might be worth switching over to highs?

**Comment by ricschuster** [comment]
> @ricschuster, I think I've got it all working now. To make updates, you should only need to edit the Rmarkdown files and GitHub Actions will automatically build the site and pdf version of the manual.
> 
> Also, once you've got this working and looking good. I wonder if it would be worth make a copy of this to serve as the "main" workshop repository, which we would simply copy as needed to create future workshops? I wonder if the template stuff on GitHub would be useful for this? What do you think?

Thanks very much @jeffreyhanson! I really appreciate your help with this.

I'm going to start making further updates now and move the code over to use `sf` and `terra`.

I like the template idea and will look into this once the repo is in good shape for my upcoming workshop.

**Comment by ricschuster** [comment]
> Also, the workshop uses lpsymphony. In terms of making the installation process easier for attendees, it might be worth switching over to highs?

Good point. Do you think it would work to use `rcbc` or are there still issues with that package on Windows machines?

**Comment by ricschuster** [comment]
One interesting/strange thing I have noticed with printing problem statements on the website is that each row it prints seems to be its own R chunk. See here for an example: https://prioritizr.github.io/NCC-workshop/gap-analysis.html#feature-abundance

@jeffreyhanson do you have an idea what could cause this?

**Comment by jeffreyhanson** [comment]
> Good point. Do you think it would work to use rcbc or are there still issues with that package on Windows machines?

Nah, rcbc seems to be fine on windows machines (as long the as the user has admin permissions to install rtools). The main reseaon I would suggest highs over rcbc for a workshop, it that mac users might potentially need to  install homebrew and the cbc homebrew packages to install the rcbc package. Whereas,  mac users can install the highs package directly from CRAN.

**Comment by jeffreyhanson** [comment]
> do you have an idea what could cause this?

Yeah, I ran into a similar issue with the vignettes for the prioritizr website. I wrote a custom print function for knitr to fix this. To use it, you can either (1) override the `print()` function at the start of the document ([like this](https://github.com/prioritizr/prioritizr/blob/master/vignettes/connectivity_tutorial.Rmd#L28-L39)), or (2) just use `p0` (instead of `print(p0)`). How does that sound?

**Comment by ricschuster** [comment]
> > Good point. Do you think it would work to use rcbc or are there still issues with that package on Windows machines?
> 
> Nah, rcbc seems to be fine on windows machines (as long the as the user has admin permissions to install rtools). The main reseaon I would suggest highs over rcbc for a workshop, it that mac users might potentially need to install homebrew and the cbc homebrew packages to install the rcbc package. Whereas, mac users can install the highs package directly from CRAN.

Lets go with highs than.

**Comment by ricschuster** [comment]
> > do you have an idea what could cause this?
> 
> Yeah, I ran into a similar issue with the vignettes for the prioritizr website. I wrote a custom print function for knitr to fix this. To use it, you can either (1) override the `print()` function at the start of the document ([like this](https://github.com/prioritizr/prioritizr/blob/master/vignettes/connectivity_tutorial.Rmd#L28-L39)), or (2) just use `p0` (instead of `print(p0)`). How does that sound?

Great! I will use option (1) to override the `print()` function if that works for you. Do you have a preference?
(I rarely use `print`)

**Comment by jeffreyhanson** [comment]
Yeah, when writing documentation, I like to use `print()` so that it's clear to the reader that the object is intentionally being printed - but that's probably my personal take.

**Comment by ricschuster** [comment]
> Yeah, when writing documentation, I like to use `print()` so that it's clear to the reader that the object is intentionally being printed - but that's probably my personal take.

That's a great point. Lets use `print()`.

**Comment by ricschuster** [comment]
> > > Good point. Do you think it would work to use rcbc or are there still issues with that package on Windows machines?
> > 
> > 
> > Nah, rcbc seems to be fine on windows machines (as long the as the user has admin permissions to install rtools). The main reseaon I would suggest highs over rcbc for a workshop, it that mac users might potentially need to install homebrew and the cbc homebrew packages to install the rcbc package. Whereas, mac users can install the highs package directly from CRAN.
> 
> Lets go with highs than.

Maybe not `highs`. I just tried installing the CRAN package on Windows and get an error message:

![image](https://user-images.githubusercontent.com/3445092/228954533-c456e87e-b4be-4de2-91ca-c054258bc64a.png)

How about `Rsymphony`? Does that have issues on Mac? I think it works fine on Windows with the CRAN package.

**Comment by jeffreyhanson** [comment]
Looks like you're installing it from source. Maybe this is because you're using R version 4.1, which doesn't have binaries available for highs (https://cran.r-project.org/web/packages/highs/index.html)?  AFAIK if you use version 4.2+ then it should be able to install the precompiled binary.

**Comment by ricschuster** [comment]
> Looks like you're installing it from source. Maybe this is because you're using R version 4.1, which doesn't have binaries available for highs (https://cran.r-project.org/web/packages/highs/index.html)? AFAIK if you use version 4.2+ then it should be able to install the precompiled binary.

You are correct. 
That's what I get from trying to use 'fancy' RStudio. Works fine on 4.2+

**Comment by jeffreyhanson** [comment]
Ah - good to know. To help prevent workshop attendees from encounting this issue, it might be worth putting a note in the workshop materials stating that R 4.2+ is required?

Lol - I think it's possible to tell Rsutdio which R version to use when there are multiple versions of R installed on a computer - but I might be wrong - I don't really use Rstudio.

**Comment by ricschuster** [comment]
> Lol - I think it's possible to tell Rsutdio which R version to use when there are multiple versions of R installed on a computer - but I might be wrong - I don't really use Rstudio.

That's what I apparently did last I used Rstudio, so it was still set to 4.1.1.

**Comment by ricschuster** [comment]
GitHub Actions currently fail and I'm pretty sure its related to this part of the code:
https://github.com/prioritizr/NCC-workshop/blob/main/04-prioritizations.Rmd#L242

It works fine locally and I'm not sure what it is.
@jeffreyhanson could you have a quick look?

**Comment by jeffreyhanson** [comment]
My guess is that `terra::rescale()` is conflicting with `scales::rescale()`. It  Maybe try something like `wts <- scales::rescale(wts, to = c(1, 10))`?

**Comment by jeffreyhanson** [comment]
Or maybe using the conflicted package to load the packages and specify how namespace conflicts should be handled? I've never used this package though.

**Comment by ricschuster** [comment]
GitHub actions complete successfully now.
@jeffreyhanson did you want to have a look over the website before we turn thus repo into the workshop template?

**Comment by jeffreyhanson** [comment]
Thanks! Yeah, I can see a few things that could be improved, should I put togeather a PR? Or were there other changes you wanted to make first?

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson! A PR would be great.

**Comment by jeffreyhanson** [comment]
Ok - will do.
